import { createHash } from 'node:crypto';
import { mkdir, readFile, stat, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { Injectable } from '@nestjs/common';
import { AppConfigService } from '../../common/config/app-config.service';

export const OBJECT_STORAGE = Symbol('OBJECT_STORAGE');

export interface StoredObject {
  key: string;
  sizeBytes: number;
  checksum: string;
}

/**
 * Port for binary objects. Callers only ever hand over a key and a buffer;
 * where the bytes live is an infrastructure decision. Development writes to a
 * local directory, production points the same port at S3/GCS-compatible
 * storage, and the domain code never changes.
 *
 * Keys are opaque but hierarchical (`tenant/.../sha256`), which makes the local
 * adapter safe to browse and lets a cloud adapter map the same key onto a
 * prefix without a translation table.
 */
export interface ObjectStorage {
  put(key: string, bytes: Buffer): Promise<StoredObject>;
  get(key: string): Promise<Buffer>;
  exists(key: string): Promise<boolean>;
}

@Injectable()
export class LocalObjectStorage implements ObjectStorage {
  private readonly root: string;

  constructor(config: AppConfigService) {
    this.root = resolve(config.storageDir);
  }

  async put(key: string, bytes: Buffer): Promise<StoredObject> {
    const target = this.pathFor(key);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, bytes);
    return {
      key,
      sizeBytes: bytes.byteLength,
      checksum: createHash('sha256').update(bytes).digest('hex'),
    };
  }

  async get(key: string): Promise<Buffer> {
    return readFile(this.pathFor(key));
  }

  async exists(key: string): Promise<boolean> {
    try {
      await stat(this.pathFor(key));
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Reject keys that would escape the storage root. Keys are generated by the
   * application, but this is the boundary where a mistyped or hostile key would
   * become a path traversal, so it is checked regardless.
   */
  private pathFor(key: string): string {
    const target = resolve(join(this.root, key));
    if (!target.startsWith(this.root)) {
      throw new Error('Storage key escapes the storage root');
    }
    return target;
  }
}
