import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { Injectable } from '@nestjs/common';
import { AppConfigService } from '../../../common/config/app-config.service';

export const DOCUMENT_STORAGE = Symbol('DOCUMENT_STORAGE');

export interface StoredObject {
  key: string;
  sizeBytes: number;
  checksum: string;
}

/**
 * Port for document bytes. The domain only ever hands over a key and a buffer;
 * whether those bytes land on local disk or in object storage is an
 * infrastructure decision. Production swaps in a provider-specific adapter
 * without touching the service.
 */
export interface DocumentStorage {
  put(key: string, bytes: Buffer): Promise<StoredObject>;
  get(key: string): Promise<Buffer>;
}

@Injectable()
export class LocalDocumentStorage implements DocumentStorage {
  private readonly root: string;

  constructor(config: AppConfigService) {
    this.root = resolve(config.documentStorageDir);
  }

  async put(key: string, bytes: Buffer): Promise<StoredObject> {
    const target = this.pathFor(key);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, bytes);
    return {
      key,
      sizeBytes: bytes.byteLength,
      checksum: createHash('sha256').update(bytes).digest('hex'),
    };
  }

  async get(key: string): Promise<Buffer> {
    return readFile(this.pathFor(key));
  }

  /**
   * Reject keys that would escape the storage root. Keys are generated by the
   * service, but this is the boundary where a mistyped or hostile key would
   * become a path traversal, so it is checked regardless.
   */
  private pathFor(key: string): string {
    const target = resolve(join(this.root, key));
    if (!target.startsWith(this.root)) {
      throw new Error('Document storage key escapes the storage root');
    }
    return target;
  }
}
