apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zion8-api
  namespace: zion8
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: zion8-api
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: zion8/api
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zion8-web
  namespace: zion8
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: zion8-web
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: zion8/web
