apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zion8
resources:
  - namespace.yaml
  - config.yaml
  - externalsecret.yaml
  - api.yaml
  - web.yaml
  - workers.yaml
  - migrate.yaml
  - hpa.yaml
  - networkpolicy.yaml
  - ingress.yaml
images:
  - name: ghcr.io/reignnrule11/zion8-api
    newTag: main
  - name: ghcr.io/reignnrule11/zion8-web
    newTag: main
  - name: ghcr.io/reignnrule11/zion8-migrate
    newTag: main
