import { z } from 'zod';

export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  FORBIDDEN: 'FORBIDDEN',
  TENANT_REQUIRED: 'TENANT_REQUIRED',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  TENANT_SLUG_TAKEN: 'TENANT_SLUG_TAKEN',
  TENANT_MEMBERSHIP_REQUIRED: 'TENANT_MEMBERSHIP_REQUIRED',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  IDENTITY_ALREADY_LINKED: 'IDENTITY_ALREADY_LINKED',
  INVALID_CHALLENGE: 'INVALID_CHALLENGE',
  CHALLENGE_EXPIRED: 'CHALLENGE_EXPIRED',
  CHALLENGE_CONSUMED: 'CHALLENGE_CONSUMED',
  MFA_REQUIRED: 'MFA_REQUIRED',
  MFA_INVALID_CODE: 'MFA_INVALID_CODE',
  MFA_FACTOR_NOT_FOUND: 'MFA_FACTOR_NOT_FOUND',
  WEBAUTHN_FAILED: 'WEBAUTHN_FAILED',
  OAUTH_FAILED: 'OAUTH_FAILED',
  OAUTH_PROVIDER_UNAVAILABLE: 'OAUTH_PROVIDER_UNAVAILABLE',
  CONTACT_NOT_VERIFIED: 'CONTACT_NOT_VERIFIED',
  ONBOARDING_STATUS: 'ONBOARDING_STATUS',
  ONBOARDING_STEP_OUT_OF_ORDER: 'ONBOARDING_STEP_OUT_OF_ORDER',
  ONBOARDING_INCOMPLETE: 'ONBOARDING_INCOMPLETE',
  ONBOARDING_ALREADY_COMPLETED: 'ONBOARDING_ALREADY_COMPLETED',
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  INVITATION_ALREADY_ACCEPTED: 'INVITATION_ALREADY_ACCEPTED',
  INVITATION_ALREADY_EXISTS: 'INVITATION_ALREADY_EXISTS',
  SUBSCRIPTION_PLAN_UNAVAILABLE: 'SUBSCRIPTION_PLAN_UNAVAILABLE',
  MEMBER_IMPORT_INVALID: 'MEMBER_IMPORT_INVALID',
  MEMBER_IMPORT_NOT_READY: 'MEMBER_IMPORT_NOT_READY',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const errorCodeSchema = z.enum(Object.values(ErrorCode) as [ErrorCode, ...ErrorCode[]]);

export const fieldIssueSchema = z.object({
  path: z.string(),
  message: z.string(),
  code: z.string().optional(),
});

export const apiErrorSchema = z.object({
  error: z.object({
    code: errorCodeSchema,
    message: z.string(),
    details: z.array(fieldIssueSchema).optional(),
    requestId: z.string().optional(),
    timestamp: z.string().datetime(),
  }),
});

export type ApiError = z.infer<typeof apiErrorSchema>;
export type FieldIssue = z.infer<typeof fieldIssueSchema>;
